### ISSUE TITLE
Erros com a atualição 2022.4.0

### ISSUE THREAD

**Issue by LeandroIssa** [hudsonbrendon/sensor.clarotv#6]
São três erros que tem apresentado na integração e com isso não esta aparecendo a programação:

1-

Este erro originou-se de uma integração personalizada.

Logger: homeassistant.helpers.entity
Source: custom_components/clarotv/sensor.py:137
Integration: clarotv (documentation)
First occurred: 16:03:57 (523 occurrences)
Last logged: 19:39:00

Update for sensor.food_network fails
Update for sensor.e fails
Update for sensor.discovery_channel fails
Update for sensor.discovery_theater_hd_3 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/clarotv/sensor.py", line 137, in update
    self._name = self._programations[0].get("line4_default")
IndexError: list index out of range

![screencapture-192-168-31-206-8123-config-logs-2022-04-07-21_35_06](https://user-images.githubusercontent.com/67451572/162340747-27075002-539d-4e16-ac78-1f1f1298a2e5.png)

2- 

Este erro originou-se de uma integração personalizada.

Logger: custom_components.clarotv.sensor
Source: custom_components/clarotv/sensor.py:88
Integration: clarotv (documentation)
First occurred: 16:03:57 (523 occurrences)
Last logged: 19:39:00

Cannot perform the request

![2](https://user-images.githubusercontent.com/67451572/162340811-20277941-336a-4d73-94d7-09826781ffae.png)

3-

Este erro originou-se de uma integração personalizada.

Logger: custom_components.clarotv.sensor
Source: custom_components/clarotv/sensor.py:61
Integration: clarotv (documentation)
First occurred: 16:03:56 (520 occurrences)
Last logged: 19:38:59

Cannot perform the request

![3](https://user-images.githubusercontent.com/67451572/162340826-fd149043-8882-46db-85a7-1145a6aa41d0.png)

**Comment by hudsonbrendon** [comment]
Corrigido!
